---
- name: "Angular Add Deployment"
  hosts: all
  become: true
  tasks:
   - name: "Copyin files"
     copy: src=./ dest=/home/ubuntu owner=ubuntu group=admin mode=755

   - name: "Deploying angular app"
     command: pm2 start /home/ubuntu/angu_deploy/app.js --name 'nodejs app'
     register: deploy

   - name: "Deploying"
     debug:
           var: deploy.stdout_lines

